services:
  bot:
    build: .
    container_name: auto_alert_bot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    environment:
      - DB_PATH=/app/data/listings.db
